

#include <iostream>
#include <vector>
#include <algorithm>
#include <functional>
#include <array>
#include <string>
#include <list>
#include <tuple>
#include <map>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <cstring>
#include <memory>
#include <optional>
#include <variant>
#include <complex>
#include <ctime>
#include <random>
#include <ranges>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <deque>
#include <queue>
#include <stack>
#include <ctime>
#include <windows.h>
#include <cinttypes>
#include <optional>
#include <any>
#include <atomic>
#include <bit>
#include <bitset>
#include <barrier>
#include <cfloat>
#include <exception>
#include <filesystem>
#include <limits>
#include <new>
#include <numbers>
#include <numeric>
#include <ratio>
#include <regex>
#include <stack>
#include <span>
#include <spanstream>
#include <thread>
#include <coroutine>
#include <concepts>
#include <utility>
#include <valarray>
#include <version>
#include <mutex>
#include <conio.h>
#include <cassert>
#include <future>
using namespace std;